config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registration => "registrations", :omniauth_callbacks => "users/omniauth_callbacks"}

  resources :users
  resources :feedbanks

  root to: 'static_pages#home'
  
  patch '/add_tidbit', to: 'users#add_tidbit'
  patch '/addNewsItem', to: 'users#add_newsItem'
  patch '/removeNewsItem', to: 'users#remove_newsItem'
  patch '/deleteNewsItem', to: 'users#mail_delete_dependencies'
  patch '/send_mail', to: 'users#send_mail'

  get '/developer',  to: 'static_pages#developer'
  get '/jobs',     to: 'static_pages#jobs'
  get '/expo', to: 'static_pages#expo'
  get '/home',      to: 'static_pages#home'
  get '/news',      to: 'static_pages#news'
  match '/mailing',      to: 'static_pages#mailing', via: [:get, :post]

  post '/modify_user_setting', to: 'users#user_update'
  post '/modify_date', to: 'users#user_date'
  post '/check_admin_updates', to: 'users#admin_updates'
  post '/request_information', to: 'users#request_info'
  post '/approve_post', to: 'users#post_approval'

  post '/search_feedbank', to: 'feedbanks#search_feedbank'
  post '/search_suggestion', to: 'feedbanks#search_suggestion' 
   
  get '/usersetting',   to: 'users#usersetting'

  match '/student_account', to: 'users#student_account', via: [:get, :post]
  match '/disable_student', to: 'users#disable_student_account', via: [:get, :post]

  match '/user_info', to: 'users#add_post', via: [:get, :post]
  get '/user_admin', to: 'users#adminPanel'
  get '/user_mail', to: 'users#mailPanel'
  patch '/generate_newsletter', to: 'users#generate_newsLetter'
  patch '/generate_newsletter_md', to: 'users#generate_newsLetter_md'
  
  get "/404" => 'users#permissiondenied'
  get "/500" => 'users#permissiondenied'

  get "/feedcreate" => 'feedbanks#create'
  patch "/feedapprove" => 'feedbanks#approve_content'
  patch "/feeddisapprove" => 'feedbanks#disapprove_content'
  get '/feedbanks/:id', to: 'feedbanks#show'

  match '/confirmation_token', to: 'users#confirmation_token', via: [:get, :post]

end

app/views/layouts/_cssHook.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'buttons' %>
<link rel='stylesheet' media="all" href='http://fonts.googleapis.com/css?family=Roboto:900,500' data-turbolinks-track="true">

app/views/layouts/_footer.html.erb
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>

<a href="https://www.facebook.com/pages/Uoft-Web-Development-Club/571896212842252" target="_blank">Follow us on Facebook</a>
<script type="text/javascript">
  $(document).ready(function() {
      if ($('textarea.ckeditor').length > 0) {
          var data = $('textarea.ckeditor');
          $.each(data, function(i) {
		   var editor = CKEDITOR.instances[data[i].id];
		   if (editor) { editor.destroy(true); }
			CKEDITOR.replace(data[i].id);
          });
      }
  });
</script>

app/views/layouts/_metatags.html.erb
<meta charset="UTF-8">
<meta name="description" content="Homepage of UofT's Web Development Club and prototype of a condensed 		email based mailing system">
<meta name="keywords" content="UofT, Web, Development, Club, Computer, Science,
	HTML, email, CSS, Javascript, Mailing">
<meta name="author" content="Web Club Developers">
<meta property="og:type" content="activity" />
<meta property="og:description" content="Homepage of UofT's Web Development Club and prototype of a 		condensed email based mailing system" />
<meta property="og:image" content="http://i.imgur.com/9m8X8Xy.jpg" />
<meta property="og:image:secure_url" content="https://www.dropbox.com/s/6x6n8quh6fspj5g/web_logo.jpg?dl=0"	  />
<meta property="og:image:width" content="200" />
<meta property="og:image:height" content="200" />

<meta name="google-site-verification" content="9zyLGCCsP8LpuIAs92t970JXaoePD6RKV6Z7Lghf1zc" />
<meta name="viewport" content="width=1024px">

app/views/layouts/_panelModule.erb
<div class="sidepanel">

<% if user_signed_in? %>
	<div class="list-group">
		<strong>Hello, <%= current_user.name %>:</strong><br>
		<a><%= link_to "My Account", "/usersetting" %> <br>
		<%= link_to "Posting Panel", "/user_info" %> <br>
		<% if current_user.account_setting.admin? %>
			<%= link_to "Admin Panel", "/user_admin" %> <br>
		<% end %>
		<% if current_user.account_setting.news_admin? %>
			<%= link_to "Mail Panel", "/user_mail" %> <br> <br>
		<% end %>
		<br>
		Sign out! <br>
		<%= link_to('Log Out', destroy_user_session_path, :method => :delete) %>
	</div>
<% else %>
	<strong>Sign In!</strong><br><br>
	<%= form_for(:user, :url => session_path(:user)) do |f| %>
	    <div class="field">
    		<%= f.label :email %><br />
   	 		<%= f.email_field :email%>
  		</div>
	    <div class="field">
		    <%= f.label :password %>
		    <% if @validatable %>
		    <em>(<%= @minimum_password_length %> characters minimum)</em>
		    <% end %><br />
		    <%= f.password_field :password, autocomplete: "off" %>
  		</div>

        <!-- Squared ONE -->
        <div class="field">
	        <div class="squaredOne userpagetop">
	            <input type="checkbox" value="None" id="squaredOne" name="check" />
	            <label for="squaredOne"></label>
	        </div>
	            
	        <span class="userpagetop marginright">Remember me</span>
	        <br>
	    </div>
	    <br>

  		<div class="actions">
    		<%= f.submit "Login", class: "btn btn-default btn-med"  %>
  		</div>

	  <%= link_to "Forgot your password?", new_password_path(:user) %> <br>
	  <%= link_to "Sign up for an account?", "/users/sign_up" %><br>
	  <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
	<% end %>
<% end %>

</div>

app/views/layouts/_secondModule.erb
<div class="second">
	<div class="second_nav">
	<ul class="second">
		<li><%= link_to "HOME".html_safe, "/" %></li>		
		<li><%= link_to "MAILING".html_safe, "/mailing" %></li>
		<li><%= link_to "DEVELOPER".html_safe, "/developer" %></li>
		<li><%= link_to "LEADERSHIP".html_safe, "/expo" %></li>
		<li><%= link_to "JOBS/RESEARCH".html_safe, "/jobs" %></li>
		<li><%= link_to "NEWS/EVENTS".html_safe, "/news" %></li>
	</ul>
	</div>
</div>

app/views/layouts/_topModule.html.erb
<div class="top">
<div class="logo"><%= link_to "Web Development Club", "/home" %></div>
<div class="loginform">
		<% if user_signed_in? %>
				<%= link_to "MY ACCOUNT".html_safe, "/useraccount" %> ::
				<%= link_to('LOGOUT', destroy_user_session_path, :method => :delete) %>
		<% else %>
		 		<%= link_to("LOGIN".html_safe, new_user_session_path) %>  
		<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>UofT Web Development Club</title>

		<%= render 'layouts/metatags' %>

		<%= csrf_meta_tags %>
		<%= render 'layouts/cssHook' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		
		<%= yield :head %> 
	</head>
	<body<% if content_for?(:body_attributes) %><%= yield(:body_attributes) %><% end %>>
	<div class="wrapper">
	<div class="topwrap">
		<%= render 'layouts/topModule' %>
		<%= render 'layouts/secondModule' %>
	</div>
		<div class="fixedWrapper">
			<div class="panelModule">
				<%= render 'layouts/panelModule' %>		
			</div>
			<div class="content">
				<%= yield %>
			</div>
		</div>
	</div>
	<div class="footer">
		<%= render 'layouts/footer' %>
	</div>

	</body>
</html>